cookie:
  expiry_days: 30
  key: some_secret_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: "Qu\u1EA3n tr\u1ECB vi\xEAn"
      password: $2b$12$E.4vRB8dVOgVM7md/u2G1.oRfECfyLFg/zQjhkv.v6J6XJ0ZbVscm
      role: admin
    sinhvien:
      email: student@example.com
      name: "Sinh vi\xEAn"
      password: $2b$12$TPnr0pqE5QgfeEBOnS72R.utjzdBvEmAzkpTw/5bxqVurgFCuVCmu
      role: sinhvien
